Task 3
Valeryshchurik/FrontendCources pull request #2
Opened 2022-05-29 07:52 UTC by Valeryshchurik

2022-06-06 19:38 UTC, alexeypt requested changes
Please, review my comments.

Also, you should add #4 task.

2022-06-06 19:38 UTC, alexeypt commented on Task3/.editorconfig
> +# editorconfig.org
I think you should add and configure root `.gitignore` for this repository. Lot's of files there shouldn't be committed.

2022-06-06 19:38 UTC, alexeypt commented on Task3/index.html
> +  <meta property="og:title" content="">
Let's discuss these tags.

2022-06-06 19:38 UTC, alexeypt commented on Task3/index.html
> +  <button onclick="setUrlParameter('x', 5)">Set url parameter</button>
It should be inside `<body>`!

2022-06-06 19:38 UTC, alexeypt commented on Task3/index.html
> +  <button onclick="printBrowserInfoStack()">Print some info</button>
Please, attach handlers to buttons with `addEventHandler` rather than using `onclick` attribute.

2022-06-06 19:38 UTC, alexeypt commented on Task3/js/main.js
> +//Create custom previous and next pages buttons on your page
Haven't you implemented this task?

2022-06-06 19:38 UTC, alexeypt commented on Task3/js/main.js
> +  let theURL              = new URL('https://dummy.com');
Hm, please, remove unnecessary spaces.

2022-06-06 19:38 UTC, alexeypt commented on Task3/js/main.js
> +function setUrlParameter(param_name, param_value){
This method doesn't work correctly on `localhost` domain. You should avoid specifying absolute url.

2022-06-06 19:38 UTC, alexeypt commented on Task3/js/main.js
> +  let theURL              = new URL('https://dummy.com');             // create dummy url
You should init empty `new URLSearchParams()` and not manipulate with absolute url.

2022-06-07 07:09 UTC, Valeryshchurik commented on Task3/js/main.js
> +//Create custom previous and next pages buttons on your page
Стрелки слева сверху. Работа с хистори

2022-07-25 09:54 UTC, alexeypt commented on Task3/.idea/.gitignore
> +# Default ignored files
I think it's better to have single root `.gitignore` where entire `.idea` folder is added as ignored.

2022-07-25 09:54 UTC, alexeypt commented on Task3/.idea/BomTask.iml
> +<?xml version="1.0" encoding="UTF-8"?>
All these files should be ignored

2022-07-25 09:54 UTC, alexeypt commented on Task3/js/main.js
> +  history.pushState(null, null, "?"+searchParams.toString());
It's better to use template strings ``?${searchParams.toString()}``.

2022-07-25 10:06 UTC, Valeryshchurik commented on Task3/.idea/BomTask.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Да, тут я ещё косячил с этим. В последних задачах всё ок с игнором

2022-07-25 10:07 UTC, Valeryshchurik commented on Task3/js/main.js
> +  history.pushState(null, null, "?"+searchParams.toString());
Учту, спасибо

2022-07-27 07:53 UTC, merged