after lint
Valeryshchurik/FrontendCources pull request #3
Opened 2022-05-29 07:59 UTC by Valeryshchurik

2022-06-06 19:42 UTC, alexeypt requested changes

2022-06-06 19:42 UTC, alexeypt commented on Task4/src/benchmark/searches.js
> +const fs = require('fs');
But where is `.eslintrc` file?

2022-06-06 19:42 UTC, alexeypt commented on Task4/src/benchmark/searches.js
> +const fs = require('fs');
Recheck this PR please.

2022-07-07 18:37 UTC, Valeryshchurik commented on Task4/.eslintrc
>  // .eslintrc
ESlint file

2022-07-27 07:53 UTC, merged